### ISSUE TITLE
C make ./ldap-sdks/ldapsdk.mk : CVSROOT is not valid, server not found

### ISSUE THREAD

**Issue by leekwunfung817** [dogtagpki/ldap-sdk#19]
@redhat8 ldap-sdks]$ make -f ldapsdk.mk
cvs  -q co -r LDAPCSDK_40_BRANCH DirectorySDKSource
Unknown host cvs-mirror.mozilla.org.
make: *** [ldapsdk.mk:78: setup] Error 1

@redhat8 ldap-sdks]$ echo $CVSROOT
:pserver:anonymous@cvs-mirror.mozilla.org:/cvsroot

Any solution?

**Comment by ckelleyRH** [comment]
I'm not sure what you are trying to do, we do not pull here from Mozilla CVS (we may have done 12 years ago).

If you are trying to build this project then you can use the `build.sh` script.

**Comment by ckelleyRH** [comment]
Closing as stale.
